restart_file: .na
start_day_local: '2021-03-22'
start_time_local: '00:00:00'
end_day_local: .na
forecast_start_day_local: '2021-03-23'
forecast_horizon: 10
forecast_project_id: CRAMPTON_runs
sim_name: CRAMPTON_works
forecast_sss_on: no
forecast_location: /Users/ryanmcclure/Documents/CRAM-forecast/glm
execute_location: /Users/ryanmcclure/Documents/CRAM-forecast/wd
