restart_file: .na
start_day_local: '2020-11-10'
start_time_local: '00:00:00'
end_day_local: .na
forecast_start_day_local: '2020-11-10'
forecast_horizon: 16.0
forecast_project_id: CRAMPTON_runs
sim_name: CRAMPTON_runs
forecast_sss_on: no
forecast_location: /home/ryan333/CRAM-forecast/forecasts
execute_location: /home/ryan333/CRAM-forecast
