restart_file: .na
start_day_local: '2020-11-10'
start_time_local: '00:00:00'
end_day_local: .na
forecast_start_day_local: '2020-11-11'
forecast_horizon: 5
forecast_project_id: CRAMPTON_runs
sim_name: CRAMPTON_works
forecast_sss_on: no
forecast_location: C:/Users/mooret/Desktop/Git/CRAM-forecast/glm
execute_location: C:/Users/mooret/Desktop/Git/CRAM-forecast/wd
