restart_file: /Users/quinn/Dropbox/Research/SSC_forecasting/run_flare_package/wrr_runs2/wrr_runs_H_2018_09_19_2018_09_20_F_16_20201119T055649.nc
start_day_local: '2020-11-10'
start_time_local: '07:00:00'
end_day_local: .na
forecast_start_day_local: '2020-11-10'
forecast_horizon: 16.0
forecast_project_id: CRAMPTON_runs
sim_name: CRAMPTON_runs
forecast_sss_on: no
forecast_location: /Users/quinn/Dropbox/Research/SSC_forecasting/run_flare_package/wrr_runs2
execute_location: /Volumes/ramdisk/working_directory
